### ISSUE TITLE
AddSetCookies regression for function types

### ISSUE THREAD

**Issue by bts** [plow-technologies/servant-auth#29]
It seems that `AddSetCookies` currently (0.2.2.0) doesn't work for function types: if I have a handler like `Int -> Handler Int` behind `Auth schemes session`, I get an `Overlapping instances` error.

For the following program,

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-7.8 --install-ghc runghc --package servant-0.9.1.1 --package servant-server-0.9.1.1 --package http-api-data-0.3.5 --package servant-auth-0.2.1.0 --package servant-auth-server-0.2.2.0 --package jose-0.5.0.0

{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE TypeOperators     #-}

import Network.Wai.Handler.Warp            (run)
import Servant
import Servant.Auth.Server
import Servant.Auth.Server.SetCookieOrphan ()

instance ToJWT ()
instance FromJWT ()

type Protected = "int" :> ReqBody '[JSON] Int :> Post '[JSON] Int
type Api auths = (Auth auths () :> Protected)

api = Proxy :: Proxy (Api '[JWT, Cookie])

intHandler :: Int -> Handler Int
intHandler = return

protected :: AuthResult () -> Server Protected
protected (Authenticated user) = intHandler
protected _                    = throwAll err401

server :: CookieSettings -> JWTSettings -> Server (Api auths)
server cs jwts = protected

main = do
  myKey <- generateKey
  let jwtCfg = defaultJWTSettings myKey
      cfg = defaultCookieSettings :. jwtCfg :. EmptyContext
  run 8000 $ serveWithContext api cfg (server defaultCookieSettings jwtCfg)
```

I get this compilation error:

```
asc-bug.hs:34:14: error:
    • Overlapping instances for Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
                                  ('Servant.Auth.Server.Internal.AddSetCookie.S
                                     ('Servant.Auth.Server.Internal.AddSetCookie.S
                                        'Servant.Auth.Server.Internal.AddSetCookie.Z))
                                  (Int -> Control.Monad.Trans.Except.ExceptT ServantErr IO Int)
                                  (Int
                                   -> Control.Monad.Trans.Except.ExceptT
                                        ServantErr
                                        IO
                                        (Headers
                                           '[Header "Set-Cookie" SetCookie,
                                             Header "Set-Cookie" SetCookie]
                                           Int))
        arising from a use of ‘serveWithContext’
      Matching instances:
        instance [overlap ok] Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
                                n oldb newb =>
                              Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
                                n (a -> oldb) (a -> newb)
          -- Defined in ‘Servant.Auth.Server.Internal.AddSetCookie’
        ...plus one instance involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the second argument of ‘($)’, namely
        ‘serveWithContext api cfg (server defaultCookieSettings jwtCfg)’
      In a stmt of a 'do' block:
        run 8000
        $ serveWithContext api cfg (server defaultCookieSettings jwtCfg)
      In the expression:
        do { myKey <- generateKey;
             let jwtCfg = defaultJWTSettings myKey
                 cfg = defaultCookieSettings :. jwtCfg :. EmptyContext;
             run 8000
             $ serveWithContext api cfg (server defaultCookieSettings jwtCfg) }
```

When I switch from servant-auth-server 0.2.2.0 back to servant-auth-server 0.2.1.0, the code compiles successfully.

**Comment by freckletonj** [comment]
I am having the same problem :( 

were you able to find the root of the problem, or fix it in the latest `servant-auth-server`?

**Comment by jkarni** [comment]
Should be fixed with #32. I'm going to blacklist 0.2.2.0 (see #25) and release this as 0.2.3.0 with the orphan instance again imported by default.

**Comment by jkarni** [comment]
I just released 0.2.3.0 - can you check that this fixes the issue?

**Comment by jkarni** [comment]
Closing - please reopen if you think that was a mistake.

**Comment by 3noch** [comment]
I'm actually still seeing this in a scenario. It seems to depend very much on how the combinators are grouped.

**Comment by 3noch** [comment]
It appears that having `"ws" :> Raw` *precede* a multi-capture endpoint causes this issue. If I move the `"ws" :> Raw` to the end (i.e. the last endpoint in the authenticated group) it works.
